/**
 * Created by admin on 15. 4. 16..
 */
var fs = require('fs');
var path = require('path');

// Replace with your unique name
exports.appName = 'RealnetworksCallPlanner';

// Use your own Server Key as generated by Google Developer Console
// For more details, see http://developer.android.com/google/gcm/gs.html
exports.gcmServerApiKey = 'AIzaSyD_yqOSMuUXWQFS57r5Q_7nTDxIcnyvtTI';

exports.notiHost = '192.168.4.59';
exports.notiPort = '3100';

// You may want to use your own credentials here
exports.apnsCertData = readCredentialsFile('apns_cert_dev.pem');
exports.apnsKeyData =readCredentialsFile('apns_key_dev.pem');

exports.authenticationEnabled = false;


//--- Helper functions ---

function readCredentialsFile(name) {
    return fs.readFileSync(
        path.resolve(__dirname, '../credentials', name),
        'UTF-8'
    );
}
